packages:
  - main
  - talks/**
  - toolbox

ignoredBuiltDependencies:
  - canvas
  - core-js
  - esbuild
  - sharp

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - playwright-chromium
  - svelte-preprocess
